# reference: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
#   kubectl exec -ti $POD_NAME -- bash
---
# kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'
# kubectl exec -it kubernetes-bootcamp-58968cc4fc-kgfw6 bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp
spec:
  selector:
    matchLabels:
      app: bootcamp
  replicas: 1
  template:
    metadata:
      labels:
        app: bootcamp
    spec:
      containers:
      - name: bootcamp
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
          name: bootcamp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
# kubectl get services/bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}' // the port is incorrect
# curl $(minikube ip):30237  
# minikube service bootcamp -v=8  // This works.
# reason: https://stackoverflow.com/questions/63283823/when-minikube-on-mac-is-asked-for-url-why-does-it-instead-start-a-service-in-a
# minikube start --no-vtx-check
# minikube config set vm-driver virtualbox
# minikube config set vm-driver docker
apiVersion: v1
kind: Service
metadata:
  name: bootcamp
  labels:
    app: bootcamp
spec:
  type: NodePort
  selector:
    app: bootcamp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: bootcamp
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bootcamp
            port: 
              number: 8080